spring.application.name=servicio-usuarios
spring.profiles.active=dev

server.port=8081
server.address=0.0.0.0

#Lo del swagger xd
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

jwt.secret=clave_secreta_secretita_:)