spring.datasource.url=jdbc:mysql://localhost:3306/db_usuario_dev
spring.datasource.username=root
spring.datasource.password=

##########El create-drop hace que cree las tablas al iniciar,
# pero se borran al apagar. Para que se guarden es update#############
spring.jpa.hibernate.ddl-auto=create-drop
########################################################################

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect