spring.application.name=servicio-usuarios

server.port=8081
server.address=0.0.0.0

spring.datasource.url=jdbc:postgresql://ep-plain-lab-ai6pwqlp-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_5FIoTwiEqmY6

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.enable-hateoas=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

jwt.secret=EstaEsUnaClaveSuperSecretaYMuyLargaParaJWT12345