spring.application.name=servicio-usuarios
spring.profiles.active=dev

server.port=8081
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/db_usuarios?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=


springdoc.enable-hateoas=false
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

jwt.secret=clave_secreta_secretita_:)